### ISSUE TITLE
Alpine Linux中abuild的默认startdir参数描述问题

### ISSUE THREAD

**Issue by Shouhua** [wenerme/wener#34]
您好，
我参考您的博客描述Alpine Linux中打包package的[页面](https://wener.me/notes/os/alpine/pkgs)，其中在“abuild”章中描述`startdir`默认参数如下：
```
startdir="${APKBUILD%/*}"
```
但是，我在官网上看到[描述](https://wiki.alpinelinux.org/wiki/APKBUILD_Reference)是如下：
```bash
startdir
The directory where the APKBUILD script is.
```
请问`startdir`参数是不是应该就是`APKBUILD`文件所在的文件夹？或者说我对`${APKBUILD%/*}`这个值有歧义？:)

**Comment by wenerme** [comment]
> `${APKBUILD%/*}` 是一种参数扩展的形式。这里，`%/*` 表示从变量的值中去除从右边开始的最短匹配 `/*` 的部分。具体来说，`/*` 匹配路径中的最后一部分（即文件名），并将其去除，只留下目录部分。

源码里是这样的

https://github.com/alpinelinux/abuild/blob/22e17446f7a8982b575180dc3bc57721d2bfc4eb/abuild.in#L2947

维护了一个小的 alpine 群组，感兴趣可以加入，或者 https://t.me/alpineos

![image](https://github.com/wenerme/wener/assets/1777211/9636f134-c00b-4029-895e-75a6541f1f27)

**Comment by Shouhua** [comment]
您说的这个是可信的，我的疑惑是用户使用时候没有设置这个APKBUILD环境变量，我使用“APKBUILD”文件作为配置文件，所以这样看起来有点疑惑。
刚刚看了您给的链接，找到了定义APKBUILD变量的[地方](https://github.com/alpinelinux/abuild/blob/0e325a2354dc04f1aa7bef7f422451a1fd2c82d4/abuild.in#L2902)，解决了疑惑。
非常感谢 :)
